In [37]:
import numpy as np

# Start with a 10x10 matrix filled with numbers 1–100
matrix = np.arange(0, 100).reshape(10, 10)

# Overwrite the first two rows
matrix[0] = 0
matrix[1] = 1

# Overwrite the last two rows
matrix[-2] = 0
matrix[-1] = 1
#after swapping
print("\nBefore swapping:")
print(matrix)

#after swapping
print("\nAfter swapping:")
matrix[[0,1]] = matrix[[1,0]]

# Swap last row with its upper row
matrix[[9,8]] = matrix[[8,9]]
print(matrix)



Before swapping:
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]]

After swapping:
[[ 1  1  1  1  1  1  1  1  1  1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 0  0  0  0  0  0  0  0  0  0]]


In [2]:
import math
def my_function(*kids):
  print("The youngest child is " + kids[2])

my_function(10, 20, 30)
# Output:
# TypeError: can only concatenate str (not "int") to str

TypeError: can only concatenate str (not "int") to str

In [38]:
import numpy as np

# Create 4 rows with 10 elements each = total 40 elements
matrix = [
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
]

matrix = np.array(matrix)          # convert to numpy array
matrix = np.reshape(matrix, (2, 20)) 

print(matrix)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]]


In [22]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [23]:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[1, 1, 0])

7


In [25]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:6])

[1 2 3 4 5 6]


In [27]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr
[::2]
)


[10 20 30 40]
