In [1]:
import numpy as np

# Start with a 10x10 matrix filled with numbers 1–100
matrix = np.arange(0, 100).reshape(10, 10)

# Overwrite the first two rows
matrix[0] = 0
matrix[1] = 1

# Overwrite the last two rows
matrix[-2] = 0
matrix[-1] = 1
#after swapping
print("\nBefore swapping:")
print(matrix)

#after swapping
print("\nAfter swapping:")
matrix[[0,1]] = matrix[[1,0]]

# Swap last row with its upper row
matrix[[9,8]] = matrix[[8,9]]
print(matrix)



Before swapping:
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]]

After swapping:
[[ 1  1  1  1  1  1  1  1  1  1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 0  0  0  0  0  0  0  0  0  0]]
