In [ ]:
import numpy as np


# Create a sample numpy matrix (2D array)
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print("Original Matrix:")
print(matrix)

# Swap first row with second row
matrix[[0, 1]] = matrix[[1, 0]]

# Swap last row with its upper row
matrix[[-1, -2]] = matrix[[-2, -1]]

print("\nMatrix after swapping:")
print(matrix)

Original Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Matrix after swapping:
[[ 4  5  6]
 [ 1  2  3]
 [10 11 12]
 [ 7  8  9]]


In [6]:
import pandas as pd
df = pd.DataFrame(matrix, columns=['temperature', 'holiday', 'age'])
print("\nDataFrame:")


DataFrame:


In [9]:
import pandas as pd
import numpy as np

# number of rows
n = 5  

# create random temperature values between 15 and 35
temperature = np.random.randint(15, 36, size=n)

# create random age values (let’s say 18 to 60)
age = np.random.randint(18, 61, size=n)

# create random holiday column with 0 or 1
holiday = np.random.randint(0, 2, size=n)

# make dataframe
df = pd.DataFrame({
    "Temperature": temperature,
    "Age": age,
    "Holiday": holiday
})

print(df)


   Temperature  Age  Holiday
0           23   26        0
1           35   22        0
2           28   23        0
3           16   49        0
4           29   47        1


In [ ]:
import pandas as pd
import numpy as np

# number of rows
n = 5  

# create random temperature values between 15 and 35
temperature = np.random.randint(15, 36, size=n,)

# create random age values (let’s say 18 to 60)
age = np.random.randint(18, 61, size=n)

# create random holiday column with 0 or 1
holiday = np.random.randint(0, 2, size=n)

# make dataframe
df = pd.DataFrame({
    "Temperature": temperature,
    "Age": age,
    "Holiday": holiday
})

# print without index
print(df.to_string(index=False))


 Temperature  Age  Holiday
          25   54        0
          31   33        1
          32   32        1
          18   48        0
          31   58        1


In [11]:
import pandas as pd
import numpy as np

# number of rows
n = 5  

# create random data
temperature = np.random.randint(15, 36, size=n)
age = np.random.randint(18, 61, size=n)
holiday = np.random.randint(0, 2, size=n)

# make dataframe
df = pd.DataFrame({
    "Temperature": temperature,
    "Age": age,
    "Holiday": holiday
})

# save to CSV (no index)
df.to_csv("mydata.csv", index=False)

print("CSV file saved as mydata.csv")


CSV file saved as mydata.csv
